---
title: "Professional Experience"
---

# Professional Experience

### Building Manager Jr  
**The Good Caretaker – Vancouver, Canada**  
*Nov 2023 – Present*

- Supervise daily operations and maintenance of building facilities to ensure a safe, clean, and efficient environment for residents.  
- Address residents’ inquiries and concerns, providing excellent customer service and resolving issues related to amenities and services.  
- Build and maintain relationships with contractors, ensuring contract compliance and high-quality service delivery.  
- Ensure compliance with all local strata regulations, including health, safety, and environmental standards.

---

### Operations Manager  
**ASAMA Solutions – TSG Fleet/ISG Inc – Los Angeles, USA**  
*Nov 2021 – Oct 2023*

- Developed and implemented operational strategies to optimize logistics, inventory, and supply chain processes.  
- Managed budgets and resources, ensuring cost-effective operations while maintaining service quality.  
- Oversaw daily operations, monitored KPIs, and improved dispatch efficiency.  
- Conducted performance evaluations and led staff training, fostering a culture of continuous improvement.  
- Prepared logistics and cost analysis reports to support strategic decision-making.

---

### Logistics Coordinator  
**Convoy – Seattle, USA**  
*Oct 2021 – Oct 2023*

- Planned and supervised logistics operations to optimize efficiency and meet delivery timelines.  
- Gathered and analyzed logistics data to enhance decision-making and process performance.  
- Coordinated shipments, monitored stock levels, and managed inventory to prevent shortages or overstocking.  
- Implemented process improvements to streamline operations and reduce costs.  
- Collaborated with warehouse, transportation, and customer service teams for seamless logistics execution.

---

### Supernumerary - Assistant Manager  
**Banco Caja Social – Bucaramanga, Colombia**  
*Oct 2019 – Sept 2021*

- Supported branch operations by assisting in cash handling, customer service, and administrative duties.  
- Ensured compliance with banking protocols, maintaining accuracy and data integrity.  
- Provided temporary assistance to various departments during high-demand periods.  
- Participated in continuous training on bank policies and operational systems.

---

 
